export const INCREASE_STEPPER = 'INCREASE_STEPPER'
export const DECREASE_STEPPER = 'DECREASE_STEPPER'

export const GET_PROJECT_INIT = 'GET_PROJECT_INIT'
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS'
export const GET_PROJECT_FAILED = 'GET_PROJECT_FAILED'

export const GET_DATASET_INIT = 'GET_DATASET_INIT'
export const GET_DATASET_SUCCESS = 'GET_DATASET_SUCCESS'
export const GET_DATASET_FAILED = 'GET_DATASET_FAILED'

export const GET_TABLE_INIT = 'GET_TABLE_INIT'
export const GET_TABLE_SUCCESS = 'GET_TABLE_SUCCESS'
export const GET_TABLE_FAILED = 'GET_TABLE_FAILED'

export const GET_SCHEMA_INIT = 'GET_SCHEMA_INIT'
export const GET_SCHEMA_SUCCESS = 'GET_SCHEMA_SUCCESS'
export const GET_SCHEMA_FAILED = 'GET_SCHEMA_FAILED'
